site_name: "Unity Job Analytics"

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings:
        handlers:
          python:

            options:
              # include type annotations in that signature
              show_signature_annotations: true
              # keep signature on the same line as the heading
              separate_signature: false
              # control how long module paths appear
              annotations_path: brief
              # choose your docstring flavor:
              docstring_style: google       # or numpy, sphinx
              # render Parameters/Returns as a table
              docstring_section_style: list

nav:
  - Home: 'index.md'
  - About: 'about.md'
  - Data:
    - 'preprocess.md'
  - Analysis:
    - 'analysis/efficiency_analysis.md'
  - Visualization:
    - 'visualization/visualization.md'
    - 'visualization/visualize_columns.md'
  - MVP Scripts:
    - 'mvp-scripts/cpu_metrics.md'
    - 'mvp-scripts/gpu_metrics.md'
    - 'mvp-scripts/zero_gpu_usage.md'

